platform :osx, '10.8'


pod 'NSDate-Extensions'
pod 'INAppStoreWindow'
pod 'AXStatusItemPopup'


pod 'BOAPI', :path => '~/Development/LocalPods/BOAPI'
pod 'DPStorage'
pod 'NSObject+AutoDescription'
pod 'WDCountdownFormatter'
pod 'NSColor-Crayola', :path => '~/Development/LocalPods/Forked/NSColor-Crayola'
pod 'DPObject', :path => '~/Development/LocalPods/DPObject'
pod 'DPWindow', :path => '~/Development/LocalPods/DPWindow'
pod 'DPKit', :path => '~/Development/LocalPods/DPKit'
pod 'DPStorage', :path => '~/Development/LocalPods/DPStorage'
pod 'DPOutlineView', :path => '~/Development/LocalPods/Controls/DPOutlineView'
pod 'NSView-DPFrameUtils'
#pod 'NSView-NewConstraints'
pod 'NSView-NewConstraints', :path => '~/Development/LocalPods/Utilities/NSView-NewConstraints'

pod 'NSColor-BlendingUtils'
pod 'DPTimer', :path => '~/Development/LocalPods/DPTimer'
pod 'BOUI', :path => '~/Development/LocalPods/BOUI'

pod 'DPStatusItemView', :path => '~/Development/LocalPods/DPStatusItemView'