platform :osx, '10.8'

pod 'BOAPI', :path => '~/Development/LocalPods/BOAPI'
pod 'DPStorage'
pod 'NSObject+AutoDescription'
pod 'WDCountdownFormatter'
pod 'DPWindow', :path => '~/Development/LocalPods/DPWindow'
pod 'DPKit', :path => '~/Development/LocalPods/DPKit'
pod 'NSView-DPFrameUtils'