platform :osx, '10.8'

pod 'BOAPI', :path => '~/Development/LocalPods/BOAPI'
pod 'DPStorage'
pod 'NSObject+AutoDescription'
pod 'WDCountdownFormatter'
pod 'NSColor-Crayola', :path => '~/Development/LocalPods/Forked/NSColor-Crayola'
pod 'DPObject', :path => '~/Development/LocalPods/DPObject'
pod 'DPWindow', :path => '~/Development/LocalPods/DPWindow'
pod 'DPKit', :path => '~/Development/LocalPods/DPKit'
pod 'DPOutlineView'
pod 'NSView-DPFrameUtils'

pod 'NSColor-BlendingUtils'